"""
자동 월간 리포트 PDF 모듈
──────────────────────────
클라이언트 담당자가 상사에게 그대로 보고할 수 있는 멀티페이지 PDF 리포트.
  Page 1: 커버 + Executive Summary (KPI 카드 4개 + MoM)
  Page 2: 매체별 성과 테이블 + TOP/하락 매체
  Page 3: 벤치마크 포지셔닝 (Firebase 연동)
  Page 4: 액션 아이템 + 다음 달 제안
"""
import os
from datetime import datetime
from io import BytesIO

import numpy as np
import pandas as pd
from fpdf import FPDF

from modules.config import (
    BRAND_PRIMARY, COLOR_BLUE, compact_num,
)
from modules.firebase_connector import (
    load_benchmark as _fb_load_benchmark,
    get_benchmark_stats, calc_percentile, calc_percentile_lower, percentile_letter,
)
from modules.data_processing import calc_ctr_scalar

# ──────────────────────────────────────────────
# 폰트 경로
# ──────────────────────────────────────────────
import platform as _platform


def _font_candidates() -> list[tuple[str, str, str]]:
    _sys = _platform.system()
    if _sys == "Windows":
        b = "C:/Windows/Fonts"
        return [
            ("MalgunGothic", f"{b}/malgun.ttf", f"{b}/malgunbd.ttf"),
            ("NanumGothic", f"{b}/NanumGothic.ttf", f"{b}/NanumGothicBold.ttf"),
        ]
    elif _sys == "Darwin":
        return [
            ("AppleGothic", "/System/Library/Fonts/Supplemental/AppleGothic.ttf",
             "/System/Library/Fonts/Supplemental/AppleGothic.ttf"),
        ]
    return [
        ("NanumGothic", "/usr/share/fonts/truetype/nanum/NanumGothic.ttf",
         "/usr/share/fonts/truetype/nanum/NanumGothicBold.ttf"),
    ]


_FONTS = _font_candidates()

# 색상 (RGB)
_C = {
    'primary': (247, 147, 29),
    'blue':    (49, 130, 246),
    'green':   (0, 200, 83),
    'red':     (244, 67, 54),
    'text':    (25, 31, 40),
    'text2':   (139, 149, 161),
    'text3':   (78, 89, 104),
    'bg':      (247, 248, 250),
    'white':   (255, 255, 255),
    'border':  (235, 238, 242),
    'card':    (250, 251, 252),
}


# ══════════════════════════════════════════════
# MonthlyPDF 클래스
# ══════════════════════════════════════════════

class MonthlyPDF(FPDF):
    """멀티페이지 한글 PDF — 월간 리포트용"""

    def __init__(self, company: str = "", period: str = ""):
        super().__init__(orientation='P', unit='mm', format='A4')
        self._register_font()
        self.set_auto_page_break(auto=True, margin=20)
        self.company = company
        self.period = period

    def _register_font(self):
        for name, regular, bold in _FONTS:
            if os.path.isfile(regular):
                self.add_font(name, '', regular, uni=True)
                if os.path.isfile(bold):
                    self.add_font(name, 'B', bold, uni=True)
                else:
                    self.add_font(name, 'B', regular, uni=True)
                self._ff = name
                return
        self._ff = 'Helvetica'

    def _f(self, style='', size=10):
        self.set_font(self._ff, style, size)

    # ── Header / Footer ──

    def header(self):
        if self.page_no() == 1:
            return  # 커버 페이지는 자체 헤더
        self._f('', 7)
        self.set_text_color(*_C['text2'])
        self.set_xy(12, 8)
        self.cell(0, 4, f"{self.company} | 월간 리포트 | {self.period}", align='L')
        self.set_draw_color(*_C['border'])
        self.line(12, 13, 198, 13)
        self.set_y(16)

    def footer(self):
        self.set_y(-15)
        self.set_draw_color(*_C['border'])
        self.line(12, self.get_y(), 198, self.get_y())
        self._f('', 7)
        self.set_text_color(*_C['text2'])
        self.cell(0, 8, f"Page {self.page_no()} | Generated by BrainCube LMS Analytics", align='C')

    # ── Drawing Helpers ──

    def draw_cover(self, company: str, period: str, gen_date: str):
        """Page 1: 커버"""
        self.add_page()
        # 배경 상단 그라디언트 영역
        self.set_fill_color(*_C['primary'])
        self.rect(0, 0, 210, 100, 'F')

        # 회사명
        self._f('B', 28)
        self.set_text_color(*_C['white'])
        self.set_xy(20, 30)
        self.cell(0, 12, company)

        # 리포트 제목
        self._f('', 14)
        self.set_xy(20, 48)
        self.cell(0, 8, "LMS 월간 성과 리포트")

        # 기간
        self._f('', 11)
        self.set_xy(20, 62)
        self.cell(0, 6, period)

        # 생성일
        self._f('', 9)
        self.set_xy(20, 74)
        self.set_text_color(200, 200, 200)
        self.cell(0, 5, f"Report Generated: {gen_date}")

        # 하단 흰색으로 복귀
        self.set_text_color(*_C['text'])
        self.set_y(110)

    def draw_kpi_cards(self, kpis: list[dict]):
        """KPI 카드 행 (4개)"""
        card_w = (186 - (len(kpis) - 1) * 3) / len(kpis)
        card_h = 24
        y0 = self.get_y()

        for i, kp in enumerate(kpis):
            x = 12 + i * (card_w + 3)
            # 카드 배경
            self.set_fill_color(*_C['card'])
            self.set_draw_color(*_C['border'])
            self.rect(x, y0, card_w, card_h, 'DF', round_corners=True, corner_radius=3)
            # 상단 악센트
            self.set_fill_color(*_C['primary'])
            self.rect(x, y0, card_w, 1.5, 'F')
            # 라벨
            self._f('', 7)
            self.set_text_color(*_C['text2'])
            self.set_xy(x + 3, y0 + 3.5)
            self.cell(card_w - 6, 4, kp['label'])
            # 값
            self._f('B', 14)
            self.set_text_color(*_C['text'])
            self.set_xy(x + 3, y0 + 9)
            self.cell(card_w - 6, 7, kp['value'])
            # 변화율
            if kp.get('delta'):
                self._f('', 7)
                dt = kp.get('delta_type', '')
                if dt == 'up':
                    self.set_text_color(*_C['red'])
                    arrow = chr(0x2191) + ' '
                elif dt == 'down':
                    self.set_text_color(*_C['blue'])
                    arrow = chr(0x2193) + ' '
                else:
                    self.set_text_color(*_C['text2'])
                    arrow = ''
                self.set_xy(x + 3, y0 + 17.5)
                self.cell(card_w - 6, 4, f"{arrow}{kp['delta']}")

        self.set_y(y0 + card_h + 5)

    def section(self, title: str, color: tuple = None):
        """섹션 소제목"""
        c = color or _C['primary']
        y0 = self.get_y()
        if y0 > 260:
            self.add_page()
            y0 = self.get_y()
        self.set_fill_color(*c)
        self.rect(12, y0, 3, 6, 'F')
        self._f('B', 11)
        self.set_text_color(*_C['text'])
        self.set_xy(17, y0)
        self.cell(0, 6, title, ln=True)
        self.set_y(self.get_y() + 2)

    def table(self, headers: list[str], rows: list[list[str]], widths: list[float]):
        """테이블"""
        rh = 6.5
        y0 = self.get_y()
        if y0 + rh * (len(rows) + 1) > 270:
            self.add_page()
            y0 = self.get_y()

        # 헤더
        self.set_fill_color(*_C['bg'])
        self._f('B', 7.5)
        self.set_text_color(*_C['text3'])
        x = 12
        for w, h in zip(widths, headers):
            self.set_xy(x, y0)
            self.cell(w, rh, h, fill=True, align='C')
            x += w
        self.set_y(y0 + rh)

        # 행
        self._f('', 7.5)
        self.set_text_color(*_C['text'])
        for ri, row in enumerate(rows):
            y = self.get_y()
            if y > 270:
                self.add_page()
                y = self.get_y()
            x = 12
            if ri % 2 == 1:
                self.set_fill_color(252, 253, 254)
            else:
                self.set_fill_color(*_C['white'])
            for w, cell in zip(widths, row):
                self.set_xy(x, y)
                a = 'R' if any(c.isdigit() for c in cell) else 'L'
                self.cell(w, rh, cell, fill=True, align=a)
                x += w
            self.set_y(y + rh)

        self.set_draw_color(*_C['border'])
        self.line(12, self.get_y(), 198, self.get_y())
        self.set_y(self.get_y() + 3)

    def bullets(self, items: list[str], color: tuple = None):
        """불릿 포인트"""
        c = color or _C['blue']
        self._f('', 8)
        self.set_text_color(*_C['text'])
        for item in items:
            y = self.get_y()
            if y > 270:
                self.add_page()
                y = self.get_y()
            self.set_fill_color(*c)
            self.ellipse(14, y + 1.5, 2, 2, 'F')
            self.set_xy(18, y)
            self.multi_cell(178, 5, item)
            self.set_y(self.get_y() + 1.5)

    def mom_bar(self, label: str, current: float, previous: float, unit: str = ""):
        """MoM 미니 비교 바"""
        y0 = self.get_y()
        if y0 > 268:
            self.add_page()
            y0 = self.get_y()
        bar_max_w = 60
        max_val = max(current, previous, 1)

        self._f('', 7.5)
        self.set_text_color(*_C['text3'])
        self.set_xy(12, y0)
        self.cell(30, 5, label)

        # 이전
        pw = max((previous / max_val) * bar_max_w, 1)
        self.set_fill_color(220, 225, 230)
        self.rect(42, y0, pw, 4.5, 'F', round_corners=True, corner_radius=1.5)
        self._f('', 6.5)
        self.set_text_color(*_C['text2'])
        self.set_xy(42 + pw + 2, y0)
        self.cell(30, 4.5, compact_num(previous, unit))

        y0 += 5.5
        cw = max((current / max_val) * bar_max_w, 1)
        self.set_fill_color(*_C['primary'])
        self.rect(42, y0, cw, 4.5, 'F', round_corners=True, corner_radius=1.5)
        self._f('B', 6.5)
        self.set_text_color(*_C['text'])
        self.set_xy(42 + cw + 2, y0)
        self.cell(30, 4.5, compact_num(current, unit))

        # 변화율
        if previous > 0:
            change = (current - previous) / previous * 100
            sign = "+" if change >= 0 else ""
            self._f('B', 7.5)
            c = _C['red'] if change > 0 else _C['blue']
            self.set_text_color(*c)
            self.set_xy(140, y0 - 3)
            self.cell(30, 5, f"{sign}{change:.1f}%", align='R')

        self.set_y(y0 + 7)

    def highlight_box(self, text: str, color: tuple = None):
        """강조 박스"""
        c = color or _C['primary']
        y0 = self.get_y()
        if y0 > 262:
            self.add_page()
            y0 = self.get_y()
        # 연한 배경색 (원본 색상에 투명도 대신 밝게 조정)
        self.set_fill_color(
            min(255, c[0] + (255 - c[0]) * 85 // 100),
            min(255, c[1] + (255 - c[1]) * 85 // 100),
            min(255, c[2] + (255 - c[2]) * 85 // 100),
        )
        self.set_draw_color(*c)
        box_h = 12
        self.rect(12, y0, 186, box_h, 'DF', round_corners=True, corner_radius=2)
        self._f('', 8)
        self.set_text_color(*_C['text'])
        self.set_xy(16, y0 + 2)
        self.multi_cell(178, 4.5, text)
        self.set_y(y0 + box_h + 3)


# ══════════════════════════════════════════════
# 데이터 분석
# ══════════════════════════════════════════════

def _compute_kpis(df: pd.DataFrame) -> list[dict]:
    total_cost = df['집행금액'].sum()
    total_send = df['발송량'].sum()
    total_click = df['클릭수'].sum()
    ctr = calc_ctr_scalar(total_click, total_send)

    months = sorted(df['년월'].unique())
    kpis = [
        {"label": "총 집행금액", "value": compact_num(total_cost, "원"), "delta": "", "delta_type": ""},
        {"label": "총 발송량", "value": compact_num(total_send, "건"), "delta": "", "delta_type": ""},
        {"label": "총 클릭수", "value": compact_num(total_click, "회"), "delta": "", "delta_type": ""},
        {"label": "평균 CTR", "value": f"{ctr:.2f}%", "delta": "", "delta_type": ""},
    ]

    if len(months) >= 2:
        curr_m, prev_m = months[-1], months[-2]
        curr = df[df['년월'] == curr_m]
        prev = df[df['년월'] == prev_m]

        def _d(cv, pv):
            if pv > 0:
                p = (cv - pv) / pv * 100
                s = "+" if p >= 0 else ""
                t = "up" if p > 0 else ("down" if p < 0 else "")
                return f"전월 대비 {s}{p:.1f}%", t
            return "", ""

        for i, col in enumerate(['집행금액', '발송량', '클릭수']):
            d, t = _d(curr[col].sum(), prev[col].sum())
            kpis[i]['delta'] = d
            kpis[i]['delta_type'] = t

        curr_ctr = calc_ctr_scalar(curr['클릭수'].sum(), curr['발송량'].sum())
        prev_ctr = calc_ctr_scalar(prev['클릭수'].sum(), prev['발송량'].sum())
        diff = curr_ctr - prev_ctr
        if abs(diff) > 0.001:
            s = "+" if diff > 0 else ""
            kpis[3]['delta'] = f"전월 대비 {s}{diff:.2f}%p"
            kpis[3]['delta_type'] = "up" if diff > 0 else "down"

    return kpis


def _media_table(df: pd.DataFrame) -> pd.DataFrame:
    m = df.groupby('매체명').agg(
        {'집행금액': 'sum', '발송량': 'sum', '클릭수': 'sum'}
    ).reset_index()
    m['CTR'] = np.where(m['발송량'] > 0, m['클릭수'] / m['발송량'] * 100, 0)
    m['CPC'] = np.where(m['클릭수'] > 0, m['집행금액'] / m['클릭수'], 0)
    return m.sort_values('클릭수', ascending=False)


def _insights(df: pd.DataFrame) -> list[str]:
    items = []
    total = df['발송량'].sum()
    clicks = df['클릭수'].sum()
    ctr = calc_ctr_scalar(clicks, total)
    items.append(f"전체 기간 평균 CTR {ctr:.2f}%, 총 {compact_num(clicks, '회')} 클릭 달성")

    media = _media_table(df)
    media_f = media[media['발송량'] >= 5000]
    if not media_f.empty:
        best = media_f.loc[media_f['CTR'].idxmax()]
        items.append(f"최고 효율 매체: {best['매체명']} (CTR {best['CTR']:.2f}%)")

    months = sorted(df['년월'].unique())
    if len(months) >= 2:
        c = df[df['년월'] == months[-1]]
        p = df[df['년월'] == months[-2]]
        c_ctr = calc_ctr_scalar(c['클릭수'].sum(), c['발송량'].sum())
        p_ctr = calc_ctr_scalar(p['클릭수'].sum(), p['발송량'].sum())
        d = c_ctr - p_ctr
        if abs(d) > 0.01:
            items.append(f"전월 대비 CTR {'상승' if d > 0 else '하락'} {abs(d):.2f}%p ({months[-2]} → {months[-1]})")

    if '요일번호' in df.columns:
        dow = df.groupby('요일번호').agg({'발송량': 'sum', '클릭수': 'sum'}).reset_index()
        dow['CTR'] = np.where(dow['발송량'] > 0, dow['클릭수'] / dow['발송량'] * 100, 0)
        if not dow.empty and dow['CTR'].max() > 0:
            b = dow.loc[dow['CTR'].idxmax()]
            names = {0: '월', 1: '화', 2: '수', 3: '목', 4: '금', 5: '토', 6: '일'}
            items.append(f"요일별 최고 효율: {names.get(int(b['요일번호']), '?')}요일 (CTR {b['CTR']:.2f}%)")

    return items[:6]


def _actions(df: pd.DataFrame) -> list[str]:
    acts = []
    media = _media_table(df)
    media_f = media[media['발송량'] >= 5000]

    if len(media_f) >= 2:
        best = media_f.loc[media_f['CTR'].idxmax()]
        worst = media_f.loc[media_f['CTR'].idxmin()]
        if best['CTR'] > worst['CTR'] * 1.3:
            acts.append(
                f"'{best['매체명']}' 매체 예산 확대 권장 "
                f"(CTR {best['CTR']:.2f}% vs '{worst['매체명']}' {worst['CTR']:.2f}%)"
            )

    if not media_f.empty:
        cpc_pos = media_f[media_f['CPC'] > 0]
        if not cpc_pos.empty:
            low = cpc_pos.loc[cpc_pos['CPC'].idxmin()]
            acts.append(f"CPC 최저 매체: '{low['매체명']}' ({low['CPC']:,.0f}원/클릭) — 비용 효율 극대화 가능")

    months = sorted(df['년월'].unique())
    if len(months) >= 2:
        for _, row in media_f.iterrows():
            nm = row['매체명']
            c = df[(df['년월'] == months[-1]) & (df['매체명'] == nm)]
            p = df[(df['년월'] == months[-2]) & (df['매체명'] == nm)]
            if c['발송량'].sum() >= 5000 and p['발송량'].sum() >= 5000:
                cc = calc_ctr_scalar(c['클릭수'].sum(), c['발송량'].sum())
                pp = calc_ctr_scalar(p['클릭수'].sum(), p['발송량'].sum())
                if pp > 0 and (pp - cc) / pp > 0.2:
                    acts.append(f"'{nm}' CTR 20%+ 하락 — 소재 교체 또는 타겟 재설정 필요")

    if not acts:
        acts.append("현재 매체별 성과가 안정적입니다. 기존 운영 전략을 유지하세요.")
    return acts[:5]


# ══════════════════════════════════════════════
# Public API
# ══════════════════════════════════════════════

def generate_monthly_pdf(
    df: pd.DataFrame,
    company_name: str = "",
    service_name: str = "",
) -> bytes:
    """멀티페이지 월간 PDF 리포트 바이트 생성."""
    if df.empty:
        raise ValueError("데이터가 비어 있어 PDF를 생성할 수 없습니다.")

    company = company_name or "LMS Analytics"
    months = sorted(df['년월'].unique())
    period = f"{months[0]} ~ {months[-1]}" if months else "전체 기간"
    gen_date = datetime.now().strftime('%Y년 %m월 %d일 %H:%M')

    pdf = MonthlyPDF(company, period)

    # ── Page 1: 커버 + KPI ──
    pdf.draw_cover(company, period, gen_date)

    pdf.section("Executive Summary")
    kpis = _compute_kpis(df)
    pdf.draw_kpi_cards(kpis)

    # MoM 비교
    if len(months) >= 2:
        pdf.section("MoM 추이", _C['primary'])
        curr_m, prev_m = months[-1], months[-2]
        curr = df[df['년월'] == curr_m]
        prev = df[df['년월'] == prev_m]

        pdf._f('', 7)
        pdf.set_text_color(*_C['text2'])
        pdf.set_x(12)
        pdf.cell(0, 4, f"{prev_m} vs {curr_m}", ln=True)
        pdf.set_y(pdf.get_y() + 1)

        for label, col, unit in [
            ("집행금액", "집행금액", "원"),
            ("발송량", "발송량", "건"),
            ("클릭수", "클릭수", "회"),
        ]:
            pdf.mom_bar(label, curr[col].sum(), prev[col].sum(), unit)

    # ── Page 2: 매체 성과 ──
    pdf.add_page()
    pdf.section("매체별 성과 상세", _C['blue'])

    media = _media_table(df)
    headers = ["매체명", "집행금액", "발송량", "클릭수", "CTR", "CPC"]
    widths = [40, 30, 30, 26, 22, 38]
    rows = []
    for _, r in media.head(15).iterrows():
        rows.append([
            str(r['매체명'])[:12],
            compact_num(r['집행금액'], "원"),
            compact_num(r['발송량'], "건"),
            compact_num(r['클릭수'], "회"),
            f"{r['CTR']:.2f}%",
            f"{r['CPC']:,.0f}원" if r['CPC'] > 0 else "-",
        ])
    pdf.table(headers, rows, widths)

    # 월별 매체 성과 (2개월 이상)
    if len(months) >= 2:
        pdf.section("월별 성과 비교", _C['primary'])
        for m in months[-3:]:  # 최근 3개월
            m_data = df[df['년월'] == m]
            cost = m_data['집행금액'].sum()
            sends = m_data['발송량'].sum()
            clicks = m_data['클릭수'].sum()
            ctr = calc_ctr_scalar(clicks, sends)
            pdf._f('', 8)
            pdf.set_text_color(*_C['text'])
            pdf.set_x(12)
            pdf.cell(0, 5, f"{m}:  {compact_num(cost, '원')}  |  "
                          f"{compact_num(sends, '건')}  |  "
                          f"{compact_num(clicks, '회')}  |  CTR {ctr:.2f}%", ln=True)

    # ── Page 3: 인사이트 + 액션 ──
    pdf.add_page()
    pdf.section("핵심 인사이트", _C['primary'])
    pdf.bullets(_insights(df), _C['primary'])

    pdf.set_y(pdf.get_y() + 3)
    pdf.section("Action Items", _C['blue'])
    pdf.bullets(_actions(df), _C['blue'])

    # 벤치마크 포지셔닝 (Firebase)
    try:
        bench = get_benchmark_stats()
    except Exception:
        bench = None
    if bench and bench['avg_ctr'] > 0:
        pdf.set_y(pdf.get_y() + 3)
        pdf.section("업종 벤치마크 포지셔닝", (108, 99, 255))

        my_send = df['발송량'].sum()
        my_click = df['클릭수'].sum()
        my_cost = df['집행금액'].sum()
        my_ctr = calc_ctr_scalar(my_click, my_send)
        my_cpc = (my_cost / my_click) if my_click > 0 else 0

        # 데이터 규모 캡션
        pdf._f('', 7)
        pdf.set_text_color(*_C['text2'])
        pdf.set_x(12)
        n_ind = len(bench.get('industries', []))
        pdf.cell(0, 4, f"Firebase {bench['total_campaigns']}건 · {n_ind}개 업종 벤치마크 기반", ln=True)
        pdf.set_y(pdf.get_y() + 2)

        # ── 비교 테이블 ──
        ctr_pct = calc_percentile(my_ctr, bench['ctr_values'])
        ctr_grade = percentile_letter(ctr_pct)
        ctr_diff = ((my_ctr - bench['avg_ctr']) / bench['avg_ctr'] * 100) if bench['avg_ctr'] > 0 else 0

        rows_data = [
            ["CTR", f"{my_ctr:.2f}%", f"{bench['avg_ctr']:.2f}%",
             ctr_grade, f"상위 {100 - ctr_pct:.0f}%",
             f"{'+'if ctr_diff >= 0 else ''}{ctr_diff:.1f}%"],
        ]
        if my_cpc > 0 and bench['avg_cpc'] > 0:
            cpc_pct = calc_percentile_lower(my_cpc, bench['cpc_values'])
            cpc_grade = percentile_letter(cpc_pct)
            cpc_diff = ((my_cpc - bench['avg_cpc']) / bench['avg_cpc'] * 100)
            rows_data.append(
                ["CPC", f"{my_cpc:,.0f}원", f"{bench['avg_cpc']:,.0f}원",
                 cpc_grade, f"상위 {100 - cpc_pct:.0f}%",
                 f"{'+'if cpc_diff >= 0 else ''}{cpc_diff:.1f}%"]
            )

        pdf.table(
            ["지표", "자사", "업종 평균", "등급", "백분위", "차이"],
            rows_data,
            [22, 30, 30, 18, 32, 30],
        )

        # ── 종합 등급 박스 ──
        all_pcts = [ctr_pct]
        if my_cpc > 0 and bench['avg_cpc'] > 0:
            all_pcts.append(cpc_pct)
        overall_pct = sum(all_pcts) / len(all_pcts)
        overall_grade = percentile_letter(overall_pct)

        grade_desc = {
            'A': '업종 상위권 — 현재 전략을 유지하며 추가 확장을 고려하세요.',
            'B': '업종 평균 이상 — 효율이 좋은 편이며 소폭 개선 여지가 있습니다.',
            'C': '업종 평균 수준 — 소재·타겟 최적화를 통해 효율을 높일 수 있습니다.',
            'D': '업종 하위권 — 소재 교체, 타겟 재설정, 발송 시간대 변경을 권장합니다.',
        }

        pdf.highlight_box(
            f"종합 등급: {overall_grade} (상위 {100 - overall_pct:.0f}%)  —  "
            f"{grade_desc.get(overall_grade, '')}",
            (108, 99, 255),
        )

    # 마무리 메시지
    pdf.set_y(pdf.get_y() + 5)
    pdf._f('', 8)
    pdf.set_text_color(*_C['text2'])
    pdf.set_x(12)
    pdf.multi_cell(186, 5,
        "본 리포트는 BrainCube LMS Analytics 시스템에서 자동 생성되었습니다. "
        "상세 분석 및 실시간 데이터는 대시보드에서 확인하세요."
    )

    buf = BytesIO()
    pdf.output(buf)
    return buf.getvalue()


# ══════════════════════════════════════════════
# Streamlit UI (탭에 등록)
# ══════════════════════════════════════════════

def render(df: pd.DataFrame):
    import streamlit as st
    from modules.config import section_header, alert_card_html

    st.markdown(section_header(
        "월간 PDF 리포트",
        "클라이언트 보고용 멀티페이지 PDF 리포트를 자동 생성합니다.",
    ), unsafe_allow_html=True)

    if df.empty:
        st.info("데이터가 없습니다. 먼저 데이터를 업로드하세요.")
        st.divider()
        return

    # 기본 정보
    company = st.session_state.get("company", "")
    months = sorted(df['년월'].unique()) if '년월' in df.columns else []

    col1, col2 = st.columns(2)
    with col1:
        company_input = st.text_input(
            "회사명 (PDF 표지)", value=company,
            key="pdf_company", placeholder="예: 브레인큐브",
        )
    with col2:
        if months:
            st.caption(f"📅 데이터 기간: {months[0]} ~ {months[-1]}")
            st.caption(f"📊 매체: {df['매체명'].nunique()}개 · 데이터: {len(df):,}건")

    # 미리보기 정보
    total_cost = df['집행금액'].sum()
    total_send = df['발송량'].sum()
    total_click = df['클릭수'].sum()
    ctr = calc_ctr_scalar(total_click, total_send)

    st.markdown(
        f'<div style="display:flex;gap:12px;margin:16px 0">'
        f'  <div style="flex:1;background:#FFF;border-radius:14px;padding:16px;'
        f'    box-shadow:0 1px 4px rgba(0,0,0,.03);text-align:center">'
        f'    <div style="font-size:.75rem;color:#8B95A1;font-weight:600">집행금액</div>'
        f'    <div style="font-weight:800;font-size:1.1rem;color:#191F28">{compact_num(total_cost, "원")}</div>'
        f'  </div>'
        f'  <div style="flex:1;background:#FFF;border-radius:14px;padding:16px;'
        f'    box-shadow:0 1px 4px rgba(0,0,0,.03);text-align:center">'
        f'    <div style="font-size:.75rem;color:#8B95A1;font-weight:600">발송량</div>'
        f'    <div style="font-weight:800;font-size:1.1rem;color:#191F28">{compact_num(total_send, "건")}</div>'
        f'  </div>'
        f'  <div style="flex:1;background:#FFF;border-radius:14px;padding:16px;'
        f'    box-shadow:0 1px 4px rgba(0,0,0,.03);text-align:center">'
        f'    <div style="font-size:.75rem;color:#8B95A1;font-weight:600">CTR</div>'
        f'    <div style="font-weight:800;font-size:1.1rem;color:#191F28">{ctr:.2f}%</div>'
        f'  </div>'
        f'  <div style="flex:1;background:#FFF;border-radius:14px;padding:16px;'
        f'    box-shadow:0 1px 4px rgba(0,0,0,.03);text-align:center">'
        f'    <div style="font-size:.75rem;color:#8B95A1;font-weight:600">매체 수</div>'
        f'    <div style="font-weight:800;font-size:1.1rem;color:#191F28">{df["매체명"].nunique()}개</div>'
        f'  </div>'
        f'</div>', unsafe_allow_html=True)

    # PDF 생성 버튼
    st.markdown("<br>", unsafe_allow_html=True)

    if st.button("📄 월간 리포트 PDF 생성", type="primary", use_container_width=True):
        with st.spinner("PDF 리포트 생성 중..."):
            try:
                pdf_bytes = generate_monthly_pdf(
                    df,
                    company_name=company_input or "LMS Analytics",
                    service_name="BrainCube LMS Analytics",
                )
                st.session_state['_monthly_pdf'] = pdf_bytes
                st.session_state['_monthly_pdf_name'] = (
                    f"{company_input or 'LMS'}_월간리포트_"
                    f"{datetime.now().strftime('%Y%m%d')}.pdf"
                )
                st.success("✅ PDF 리포트가 생성되었습니다!")
            except Exception as e:
                st.error(f"PDF 생성 실패: {e}")

    if '_monthly_pdf' in st.session_state:
        st.download_button(
            label="⬇️ PDF 다운로드",
            data=st.session_state['_monthly_pdf'],
            file_name=st.session_state.get('_monthly_pdf_name', 'monthly_report.pdf'),
            mime="application/pdf",
            use_container_width=True,
        )

        st.markdown(alert_card_html(
            "success", "리포트 생성 완료",
            "멀티페이지 PDF가 준비되었습니다. "
            "커버 + KPI 요약 + 매체별 성과 + 인사이트 + 액션 아이템이 포함되어 있습니다.",
        ), unsafe_allow_html=True)

    st.divider()
